mozilla-extensions/mozilla-vpn-extension

.gitignore, CODE_OF_CONDUCT.md, package-lock.json, package.json, src/manifest.json
Currently running through the web-ext taskcluster guide. 
We need some files for that to work, so adding a basic skeleton, i mostly looked at secure-proxy :D
=> [Stack 00]: Add an empty Extension Project

.taskcluster.yml, package.json
> [!IMPORTANT]  
> This is a stack an based on top of #2, please review before. 
This add's a basic taskcluster config. This will create tasks for the things defined in package.json
=> [Stack 01]: Add Basic Taskcluster Definiton

web-ext-config.cjs
=> Update web-ext-config to open to 'this-firefox' tab in about:debugging

src/components/serverlist.js, src/manifest.json, src/ui/browserAction/popup.html, src/ui/browserAction/popup.js
Unbreaking a few things that I broke when I moved the popup into the browserAction/ directory so that we can again see the server list!
=> Fix server list / popup paths

src/components/serverlist.js
Stuff was not properly aligned :)
=> Polish: Fix serverlist alignment

package.json, src/shared/ipc.js, tests/jest/utils/ipc.test.mjs
The test suit complains about leaking handles, so let's fix that :)
=> Fix leaking test

src/background/vpncontroller/states.js, src/background/vpncontroller/vpncontroller.js, src/components/vpncard.js, src/ui/browserAction/popupPage.js
> [!NOTE]
> Depends on https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9776/files
Pulls the connection timestamp from the VPN state, allowing them to sync.
=> Polish: Get Time from the VPN client

src/components/stackview.js
Super subtle polish tweaks to our StackView animations. Here are the changes on top of everything in #46 . 
https://github.com/user-attachments/assets/47cdfb16-253d-4577-bf29-bb0bd47fef39
=> A few mods to our favorite stackview

src/ui/browserAction/popupPage.js, src/ui/variables.css
https://github.com/user-attachments/assets/9e9feff2-322f-4c3f-8897-0f7c888f9790
Here we:
- Fix the UI overflow and scrolling
- Consistently show the reset button and enable/disable it as the checkbox is clicked or as a location is set for the site.
=> FXVPN-156: Issues with extended popup view

src/components/vpncard.js, src/ui/variables.css
Updates the background color of the toggle and adds interaction states when the toggle is hovered and pressed.
=> FXVPN-171 : Fix toggle colors and add interaction states

src/background/requestHandler.js
Restores request filtering by RequestDetails.url. Fixes location detection on mylocation.org for PM :)
=> Restore request filtering by url (

src/ui/browserAction/popup.html, src/ui/browserAction/popupPage.js
=> Fix FXVPN-178

src/components/serverlist.js
=> Fix setting locations after searching

src/background/extensionController/states.js, src/components/vpncard.js, src/ui/browserAction/popupPage.js
Adds semi-placeholder connecting UI.
=> Add state connecting

src/components/styles.js, src/components/titlebar.js, src/components/vpncard.js, src/ui/browserAction/popupPage.js, src/ui/variables.css
This PR addresses two font nits from [FXVPN-170](https://mozilla-hub.atlassian.net/browse/FXVPN-170) & [FXVPN-171](https://mozilla-hub.atlassian.net/browse/FXVPN-171):
=> FXVPN-170-171: Fix UI nits

src/components/styles.js
=> Remove stray 'n' from styles.js

src/ui/browserAction/popupPage.js
https://github.com/user-attachments/assets/90b1f544-718e-4e0b-8313-05f904e00507
=> FXVPN-237: Fix server list scrolling

src/components/styles.js, src/ui/variables.css
This fixes the "in use" label in dark mode and changes the background color of the popup panel in darkmode to match Firefox.
=> No ticket: Fix two dark mode nits reported by foxfooder

src/components/conditional-view.js, tests/jest/components/conditional-view.test.mjs
Let's unmount all unseen screens from the dom, similar to the stack view. 
That should make it unlikely more then one get's renedered :)
=> FXVPN-236 - make sure no 2 slots could be rendered

src/components/conditional-view.js, src/ui/browserAction/popup.css, src/ui/browserAction/popup.html, tests/jest/components/conditional-view.test.mjs
- Revert "FXVPN-236 - make sure no 2 slots could be rendered (#102)"
- try again
=> Fix display issues with css instead of js

src/_locales/en/messages.json, src/background/main.js, src/background/tabHandler.js
=> Add localized titles for page action icons

src/_locales/en/messages.json
– Fix strings
- Use … and ’ in strings
- Remove extra trailing spaces in comments and strings
- Consistency in comment style (closing period)
=> Fix issues in strings file

src/_locales/en/messages.json
Leftovers from the sample: https://github.com/mdn/webextensions-examples/blob/main/notify-link-clicks-i18n/_locales/en/messages.json
=> remove copy pasted strings

.github/workflows/i18n_update.yaml
tldr; This is essentially a copy of the vpn i18n updater, just without the auto approval - need to add this to main. After that i can play around if we can just have gh ignore that, given breakage from that repo is unlikely.
=> Auto create PR's to fetch new strings 

src/ui/settingsPage/settingsPage.js, src/ui/settingsPage/tableElement.js, src/ui/variables.css
=> FXVPN-228: Settings page updates

src/background/conflictObserver.js, src/background/main.js, src/manifest.json, tests/jest/background/conflictTest.test.mjs
- Add a class to detect install conflicts
- Fix import
=> FXVPN-278 - Add an handler to detect possible conflicting addons

README.md
This PR beefs up the build steps in the README to make the project a bit friendlier to newcomers.
=> Add more build info to the readme

.github/CODEOWNERS
Not all PR's have a reviewer, so let's add us as owners, so any PR will auto get us notified to review.
=> Add a codeowner file

README.md, package-lock.json, package.json
Given the grief with `.github`, flod reached out to the web-ext team and they suggested we do it similar to relay: 
https://github.com/mozilla/fx-private-relay-add-on/blob/main/package.json#L30-L34
=> Add npm tools to help handling of .github folder in _locales

src/background/vpncontroller/states.js, src/background/vpncontroller/vpncontroller.js
Compantion to https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10042 - populate the data into the extension
=> Fetch active interventions

src/background/vpncontroller/states.js, src/background/vpncontroller/vpncontroller.js, tests/jest/background/vpncontroller/vpncontroller.test.mjs, tests/jest/utils/property.test.mjs
- we did not remove the port on errors, 
- response.error was unhandled
- Also add tests.
=> FXVPN-87 Fix installation detection

src/components/prefab-screens.js
Updates a string ID. Companion PR to https://github.com/mozilla-l10n/mozilla-vpn-extension-l10n/pull/5/files.
=> FXVPN-306: Update string id

src/ui/browserAction/popupPage.js
Fetches intervention list from the client when opening the popup
=> Actually fetch interventions from client

src/components/message-screen.js, src/components/styles.js, src/ui/firstRun/firstRun.js
This PR adds a 'next' button to the first run telemetry screen that opens the browserAction popup onClick.
https://github.com/user-attachments/assets/fca44294-7bf1-425c-b132-21bc172f0fe8
=> FXVPN-341: Add 'next' button to first run telemetry screen

jest.config.mjs, package.json, src/background/vpncontroller/states.js, src/background/vpncontroller/vpncontroller.js, src/shared/constants.js, src/shared/utils.js, tests/jest/background/utils.test.mjs, tests/jest/background/vpncontroller/vpncontroller.test.mjs
i'm about to merge changes that require a VPN update. so let's force 2.26.
=> Bump Min Version

src/background/proxyHandler/proxyHandler.js
See also: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10282
=> FXVPN-381 Use Local Proxy for DNS resolution

src/background/main.js, src/background/vpncontroller/states.js, src/background/vpncontroller/vpncontroller.js, src/components/vpncard.js, src/ui/browserAction/popupPage.js
https://github.com/user-attachments/assets/b40f42ac-69e6-45ba-a273-a0f9cf6c7af1
=> Add MultiHop UI

src/components/prefab-screens.js, src/ui/browserAction/popupConditional.js
Updates the Strings used in the subnow screen to: 
Requires this to merge: https://github.com/mozilla-l10n/mozilla-vpn-extension-l10n/pull/9
=> Update Subscribe Now Strings

src/components/prefab-screens.js
=> Add Get Help Button to the Split-Tunnel Message

docs/create-a-release.md
While we're currently doing this, let's document it.
=> Add docs on how to release

src/ui/firstRun/firstRun.js
This was great feedback from david, let's do that.
=> Auto close first-run page after clicking next

src/components/butter-bar.js
Another one from our accessibility audit. Pulled this into its own PR as it depends on https://github.com/mozilla-l10n/mozilla-vpn-extension-l10n/pull/11
=> FXVPN-444: Add title and aria label to X close button

src/components/message-screen.js, src/ui/firstRun/firstRun.js
This PR contains a few quick fixes for issues unearthed in the recent accessibility audit. 
Fixes FXVPN-429, 431, 434, 436, 427, 433, 437.
=> Low hanging a11y fixes

src/background/requestHandler.js
This PR adds docs on how we filter webrequests
* **PR #239**
* **PR #241**
* **PR #242** 👈
This tree was auto-generated by [Charcoal](https://github.com/danerwilliams/charcoal)
=> Better document RequestHandler
