web-ext-config.js

Adding a web-ext config file so that when we `npm start` the extension automagically opens in Nightly, on `about:debugging`, with a browser console open.

Nice to have: Add web-ext config file 

---

.gitignore
src/background/requestHandler.js
src/background/vpncontroller/vpncontroller.js
src/utils/property.js
tests/jest/utils/property.test.mjs

This adds a small Property System capable of 1-Way, 2-Way bindings and lazy computed binding evaluation. 
Usage: 
```js
const obj = { x: "hello" };
const prop = property(obj);
let maybeValue = null;
prop.subscribe((v) => (maybeValue = v));
prop.set({ value: "UPDATED" });
expect(maybeValue).not.toBeNull();
```
I also change the VPNController to use that instead of it's own subscribtion logic

add observable properties

---

src/background/proxyHandler/proxyHandler.js
src/background/tabHandler.js

Small refactor to pass messages ("add-context", "remove-context", etc) from pageAction.js to ProxyHandler directly through ports, instead of through TabHandler as an intermediary.

Pass messages to ProxyHandler from UI via ports

---

src/ui/browserAction/popupPage.js

Currently the Popup only takes the opener page into account. Let's make it follow pages, while switching. Should make it better to demo
https://github.com/user-attachments/assets/e65c1d8c-d052-4c97-9792-8bd0cd5ad31a

Polish: Make The Popup Follow the Active Tab Context

---

src/_locales/en/messages.json
src/components/vpncard.js
src/manifest.json
src/shared/i18n.js
src/ui/browserAction/popupPage.js
src/ui/pageAction/pageAction.js

I think we're at the point where we should move things into messages.json. 
This adds a small directive to easily fetch a string and error out if we dont have one.

Add i18n support

---

src/components/vpncard.js
src/ui/browserAction/popupPage.js

Currently we don't handle "VPN Client unavailable" not really. We envision the that the extension should start the client using the native messaging app. So i would suggest we should have a "we're loading things" ui to represent this. 
https://github.com/user-attachments/assets/093a04cc-5438-4d71-9cfa-9003d7ed01ce

Polish: Add Placeholder ui for a State "Unavailable"

---

src/background/main.js
src/background/proxyHandler/proxyHandler.js
src/background/tabReloader.js
tests/jest/background/tabreloader.test.mjs

This add's a class that will listen to changes in proxyHandler. It will reload active impacted tabs by the change. Not active tabs will be discarded, and reloaded on the next activation. (As we probably dont want to reload all of my 100 jira tabs that i have not been touching). 
Also this will not reload "audible" tabs, so that a "background youtube tab" is not reloaded if you change another youtube rule.

Add a Component that will Reload Tabs if needed

---

src/ui/browserAction/popup.html
src/ui/pageAction/pageActionPopup.html
src/ui/settingsPage/index.html

Let's add a csp so the extension cannot connect to remote things. 
Also makes sure to only load .js that is inside the extension, so xss'ing an input field is quite a bit harder :)

Add CSP to content pages

---

src/ui/browserAction/popupPage.js

Let's make sure when we open the browser action we always query a new status.

Refresh status on opening of the browserAction

---

src/components/vpncard.js
src/ui/variables.css

Tiniest PR to add a drop-shadow to vpn-card.

Add drop shadow to vpn-card

---

src/ui/browserAction/popupPage.js

Fixes a tiny checkbox alignment nit I noticed while doing other things.

Vertically center checkbox with first line of label

---

src/_locales/en/messages.json
src/components/iconbutton.js
src/components/styles.js
src/components/titlebar.js
src/ui/browserAction/popupPage.js

https://github.com/user-attachments/assets/a9dd0d66-fb3b-46a0-b889-5f31ddbe2067

UI & a11y updates for the title bar icon buttons

---

src/ui/browserAction/popupPage.js

Adds support for nested bold hostname in popup string.

Add support for nested bold hostname in popup string

---

package.json

This PR adds "npm run start-dev" where we disable autohiding of popups in the hopes of stemming the tide of "would never happen in the wild bugs" like https://mozilla-hub.atlassian.net/browse/FXVPN-159.

Add npm run start-dev

---

src/components/iconbutton.js

This moves the clickHandler for iconbutons to the <button> elem instead of the nested <img> so that the entire button area is clickable, instead of just the nested image height/width.

IconButton: Move click handler to button instead of image

---

src/_locales/en/messages.json
src/components/serverlist.js
src/shared/utils.js
src/ui/browserAction/popupPage.js
tests/jest/components/serverlist.test.mjs

FXVPN-141 Nits for the serverlist

---

src/background/tabHandler.js
src/components/vpncard.js
src/ui/browserAction/popupPage.js
src/ui/pageAction/pageAction.js

Adds `.toUpperCase()` to fix flags in dist builds (which are currently broken everywhere except the server list).

Fix flags in dist builds

---

src/components/styles.js
src/components/vpncard.js
src/ui/browserAction/popupPage.js
src/ui/variables.css

Here we:
- Remove the "in-use" label from vpn-card (FXVPN-169)
- Add an "in-use" label to the location picker button that is 
- visible when a site-specific location setting is not in effect 
- hidden when the site is excluded
- disable the location picker button when the site is excluded (FXVPN-167)
- Makes some opportunistic UI tweaks

Update in-use label and location picker behavior 

---

src/background/tabHandler.js
src/background/toolbarIconHandler.js

This PR:
- A follow up PR that makes small tweaks to the tool bar icon handler to support private browsing windows where the browser chrome is dark and the extension's icon should be light. 
- Opportunistically fixes a small error in tabHandler.js noticed while debugging
This patch was merged into an XPI and verified by QA in [FXVPN-204](https://mozilla-hub.atlassian.net/browse/FXVPN-204)

Fix toolbar icon in private browsing mode

---

src/_locales/en/messages.json
src/ui/browserAction/popupPage.js

Mostly apostrophes, but also improving comments.
I assume the extra spaces in `exludePageFor` (fixed typo too) are not wanted?

Clean up English localization file

---

.github/workflows/main.yaml
src/background/extensionController/extensionController.js
src/background/extensionController/states.js
src/background/vpncontroller/states.js
src/background/vpncontroller/vpncontroller.js
src/ui/browserAction/popupPage.js
tests/jest/background/extensionController.js/extencontrollerTimer.test.mjs
tests/jest/background/extensionController.js/vpnstates.test.mjs
tests/jest/background/vpncontroller/vpncontroller.test.mjs

This moves the timer from the vpn-controller timer to the extension-controller. Also adding a few tests for that class. 
https://github.com/user-attachments/assets/4b6d655d-ed42-47ed-a914-d714e63b7e07

FXVPN-201 - Decouple timers

---

src/components/styles.js
src/ui/browserAction/popupPage.js

Fixes the tiniest alignment issue in the main panel.
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

No ticket: fix tiny alignment issue

---

src/background/vpncontroller/vpncontroller.js

RN we only call initNM once. 
So if you install the client, that wont be picked up until you re-open firefox. 
Let's remove the port on a closing/not found error and potentially re-init nm if there is no current port. 
This will cause the opening of any panel to auto re-connect if you just installed. 
https://github.com/user-attachments/assets/05198866-1774-463c-9c68-66b05d735f28

FXVPN-87 Pick up a new install

---

src/components/prefab-screens.js

This PR removes the 'Open Mozilla VPN' button from the sign-in needed error panel. There is no dedicated ticket for this but see [this Jira comment ](https://mozilla-hub.atlassian.net/browse/FXVPN-193?focusedCommentId=956275)for the decision to remove it.

Remove 'Open Mozilla VPN' button from error message

---

src/components/message-screen.js

<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

Fix content alignment in error panels

---

src/background/proxyHandler/proxyHandler.js

This is a companion PR to mozilla-mobile/mozilla-vpn-client#9952 that implements Linux support by connecting to the SOCKS proxy as a systemd service. Basically all we do here is check if the platform is `linux` and set the bypass proxy to `{type: "socks", host: "file:/var/run/mozillavpn.proxy", port: 1234}` The port number here isn't used, but it seems to be required in order to be parsed as a valid proxy.
Update! Now it supports connecting to the Windows proxy service too. Similar logic, we just check the platform and generate a fixed proxy config.

Implement Linux support via UNIX socket proxy

---

src/ui/browserAction/popup.css

Fixes visibility of error message body copy. 
<table>
<tr>
<th>before</th>
<th>after</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

Unhide error copy

---

src/background/requestHandler.js
src/background/tabHandler.js
src/background/tabReloader.js
src/shared/utils.js
src/ui/browserAction/popupPage.js
src/ui/pageAction/pageAction.js
tests/jest/background/utils.test.mjs

This PR changes `Utils.getFormattedHostname` to `Utils.getDomainName`. Instead of returning a formatted hostname, the function now takes in a url and returns the domain name. The net net of this change is that we now set proxy settings at the domain level instead of the subdomain level. 
- FXVPN-190, FXVPN-183

FXVPN-190: Set proxy settings to domains, not subdomains

---

src/background/vpncontroller/states.js
src/background/vpncontroller/vpncontroller.js

So far we only used `post_to_app` as a simple command thing. 
In fact the protocol support passing objects around. 
This will be important once we start adding commands with arguments i.e telemetry.

Allow arguments to postapp

---

src/background/vpncontroller/vpncontroller.js
src/shared/utils.js
src/ui/browserAction/popupConditional.js
src/ui/browserAction/popupPage.js

This PR: 
- Sets the `webExtension` flag to false by default. 
- This prevents folks on unsupported platforms with older versions of the client (which predate the `webExtension` flag) from being shown the the "Update now" panel instead of the "Unsupported Platform" panel. Tested this with a v2.24.2 on mac.
- Identifies the OS with `await browser.runtime.getPlatformInfo()` and uses this to conditionally show the unsupported platform panel.
- Preserves the ability for people on unsupported platforms to use the extension by enabling the `webExtension` flag.
- Requests the `featurelist` when the popup is opened to catch changes to the `webExtension` flag
A side-effect of this PR is that Windows users who flag off `webExtension` flag will not see any changes in the extension. Given the …

FXVPN-293: Improve Unsupported Platform message visibility

---

src/components/vpncard.js

We currenlty only enable the timer if the "enabled" property changes. 
However if the element was created with `enabled=true` that will not change it, therefore we never update it. 
Let's double check also in `firstUpdate`, which is just after the first render to html.

FXVPN-264 - Update the timer on first update

---

src/ui/browserAction/popupConditional.js

In FXVPN-60, QA commented that when using the extension with older versions of the client they see the `MessageSignIn` screen instead of the `MessageUpdateClient` screen. Outdated clients, depending on the version, can meet the criteria for multiple error messages so this PR reorders the conditional block in popupConditional.js so that  `needsUpdate` is just after the installation check.
<table>
<tr>
<th>
v2.20
</th>
<th>
v2.21
</th>
<th>
v2.22
</th>
<th>
v2.26
</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
Note that pre v2.20 clients and earlier do not include the mozilla vpn extension in their manifest so we have no way of communicating with them.

Fix 'needs update' error message visibility

---

src/background/vpncontroller/states.js
src/background/vpncontroller/vpncontroller.js
tests/jest/background/vpncontroller/vpncontroller.test.mjs

Companion PR: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10112/files
This PR adds the VPNController functions to reflect and modify certain VPN Client settings.

FXVPN-12 - Allow Extension to set Client Telemetry Setting

---

package.json
src/background/proxyHandler/proxyHandler.js
src/background/proxyHandler/proxyUtils.js
tests/jest/background/proxyHandler/proxyUtils.test.mjs

Ugh - it seems somehow we only get an `{}` in the browser.sync.onchanged. 
I'm not quite sure what is causing this.

Switch to localstorage

---

src/components/styles.js
src/components/vpncard.js
src/ui/variables.css

Here we: 
- Add a 'Learn more' link to the popup copy when the extension is Off and the client is On
- Make reasonable/best-guess affordances for dark mode

Add in-copy 'Learn more' link to VPNCard sub-header

---

src/background/butterBarService.js
src/background/conflictObserver.js
src/components/butter-bar.js
tests/jest/background/butterBarService.test.mjs
tests/jest/background/conflictTest.test.mjs

This is a follow up to #146 because I overlooked the following acceptance criteria:
`The warning disappears on its own when all proxy-setting extensions are inactive / removed.` 
Ergo, this PR:
- Automagically hides butter bar alerts when conflicting extensions are disabled and removed 
- Does not add these alerts to the list of dismissed alerts so that they are eligible to be shown again, should the same conflict or another conflict re-materialize 
- Renames the fn exposed to the UI from `removeAlert` -> `dismissAlert` 
- Dismissed alerts _are_ added to the dismissed alert list and are not shown again, regardless of the status of the conflict.
- Updates and adds tests

Automagically hide butter bars

---

src/background/requestHandler.js
src/shared/property.js
src/ui/browserAction/popupConditional.js
tests/jest/utils/property.test.mjs

- `computed` can be created without a type, so let's remove the class backing it. 
In #142 Matt hit a thing where a sum of more then 2 elements is required, let's refactor propertySum to work with N elements, and add tests for it :)

Allow propertySum to consume any amount of properties

---

src/background/vpncontroller/vpncontroller.js
src/shared/property.js
tests/jest/background/vpncontroller/vpncontroller.test.mjs
tests/jest/utils/property.test.mjs

- **Make sure also initial values are immutable**
- **Fix handleBridgeResponse**

basti/fix handleBrigeResponse

---

src/components/butter-bar.js
src/components/vpncard.js
src/ui/browserAction/popup.css
src/ui/browserAction/popupPage.js
src/ui/variables.css

Minor CSS changes to fix FXVPN-307 and FXVPN-302. Primarily allows scrolling on the main panel so that buttons may be accessed when butter bars are visible.

Allow main popup panel to scroll

---

src/background/extensionController/extensionController.js
tests/jest/background/extensionController.js/extencontrollerTimer.test.mjs

Slight tweak to the extension controller to change when we stipulate `mKeepAliveConnection = true` and when we call `activate` after a client deactivation.
The revised behavior is this:
1. Extension is activated while client is off ->(client is in StateOnPartial, extension is On, mkeepAliveConnection = true)
2. Client is later activated -> (now both extension and client are activated)
3. Client is deactivated -> (extension calls "activate" to reactivate the client into StateOnPartial)

FXVPN-304: Fix erroneous extension activations

---

src/ui/browserAction/popupConditional.js
src/ui/browserAction/popupPage.js
src/ui/variables.css

Fixes a UI nit that I introduced earlier in the day... observe the margin between the purple box and the bottom of the panel. The missing flag image can be ignored - Mullvad staging quirk.
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

Fixing a UI nittlynit I introced earlier today

---

src/components/vpncard.js

Hides connection stability text when the extension is off but the client is On with an Unstable or NoSignal connection

Hide client stability when extension is Off

---

src/background/vpncontroller/states.js

This PR enables telemetry in the extension by default, even if the client is not installed. Note that in this state, although telemetry is 'enabled', pings won't be sent to Glean until the client has been installed and is able to do so.

FXVPN-328: Enable telemetry by default

---

src/ui/browserAction/popup.css
src/ui/browserAction/popupPage.js

So windows 10 is wierd!  The scrollbars we see are on the window, so we need to assert we don't overflow. 
Then for the stack view i use the max window height to manually force an overflow from there if the content is too large. 
I've tested this on w11 and here is w10:

Manual Overflows

---

src/background/vpncontroller/vpncontroller.js
src/ui/firstRun/firstRun.js
tests/jest/background/vpncontroller/vpncontroller.test.mjs

```js 
if (response.settings[k]){
// import
}
```
obviously does not work if your value is false. And the test just tried to import it's own value, so that did not catch it. lmao.

FXVPN-357 fix settings import

---

src/shared/ipc.js
src/ui/browserAction/backend.js
src/ui/browserAction/popup-placeholder.js
src/ui/browserAction/popup.css
src/ui/browserAction/popup.html

If you look closely on the Screen Recording Shared with QA, you see the Red dot on the Icon not appearing for quite a while. 
This indicates firefox takes it's time inizializing the background script. 
You can easily replicate that by dropping `    await new Promise((r) => setTimeout(r, Math.round(Math.random() * 5000)));` somewhere in `main::init()`. 
Currently if we open the message port before the background script is done inizializing we are screaming into the void. 
Sooo, let's allow ipc.js to close and re-open ports if there is noone answering on the other side. 
For that ofc we need to show "Something" so i'm bringing back the loading screen we added and then removed. 🙈 
Here is a demo with a random delay.

FXVPN-337 Return of the loading screen

---

src/components/prefab-screens.js

Both are the same text, one has the "." at the end so let's not use that.

FXVPN-391 Fix button label

---

.github/workflows/main.yaml

We're currently not running that, so that makes it hard for QA to get builds :)

Other: Run CI for release branches

---

src/background/proxyHandler/proxyUtils.js
src/background/requestHandler.js

This is a small tweak to the work of #205 . This checks that a browser proxy settings is !-- "none" _and_ that a proxy URL has been provided. Otherwise it is entirely possible for someone to choose 'Manual proxy configuration', enter no URL, and then experience FXVPN-409 (which is I suspect what happened in Raluca's case). 
I will add tests in the AM :) 
Also: There is the matter of the 'Use system proxy settings' option in browser proxy settings that I'm not sure how to handle or what to do with. This PR would (I think) overwrite the system proxy setting (unless a proxy URL is automagically attached to the proxy setting object) so maybe that is a tweak that needs to be made.

Fix FXVPN-409

---

src/background/proxyHandler/proxyUtils.js
src/background/requestHandler.js
src/background/toolbarIconHandler.js

Fixes [FXVPN-412](https://mozilla-hub.atlassian.net/browse/FXVPN-412) - Sites with custom locations are broken when the client and extension are off if a browser level proxy setting exists. This patch modifies `proxyAllReqsByDefault` to return true when:
1. the client is On and the Extension is Off (extState.bypassTunnel == true)
2. the Client is Off and the Extension is On
3. the Client _and_ extension are both on _and_ a browser level proxy setting is present (we previously weren't removing the req listener when a browser level  proxy setting was present, thus bricking sites with custom geolocation settings)

Fix FXVPN-412

---

src/manifest.json

Given we now are on .25 Epic. (Should we rename that epic to 1.25 tho?)

Bump Ext-Version

---

.github/workflows/release.yaml

The default gh-release sources do not include the languages, so let's also generate an amo ready source bundle when we create a draft release :)

Upload AMO Ready source bundle

---

src/background/availabilityService.js
src/background/main.js
src/background/vpncontroller/states.js
src/background/vpncontroller/vpncontroller.js
src/components/prefab-screens.js
src/ui/browserAction/backend.js
src/ui/browserAction/popupConditional.js
tests/jest/background/availabilityService.test.mjs

Needs Final Content. 
The idea is simple, bedrock knows whether or not a client can buy the vpn in the current locale. 
Given bedrock also does not have an api endpoint for the `vpn_available(request)` func, i'm simply loading the page in the background and use their ui-test identifiers to check if the waitlist will be shown. 
That way we can save people quite some lifetime and hopefully some frustration. 
https://github.com/user-attachments/assets/9f5e9996-4015-4a9c-b55b-6c5e2cb67b07

FXVPN-440 Check Subscription Purchase Availability

---

src/background/availabilityService.js
src/shared/ipc.js
src/shared/property.js
tests/jest/utils/property.test.mjs

By doing simple equality check we can save about 20% of property.subscriptions that do absolutely nothing on startup/ opening the popup.

Dedupe all property things
